// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlakdudekbwsiyujnvka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsYWtkdWRla2J3c2l5dWpudmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NDM0MDEsImV4cCI6MjA3MTMxOTQwMX0.NKzHFbWztD6tXByNhyUHtSp46MdRsSl5tCWD4UMrxOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});